- Makefile
normally we have Sirupsen under vendor/github.com, but lack of sirupsen.
if sirupsen no exists, then create a link to Sirupsen
> fix: godeps recursive by Sirupsen, issue #0

- bcs-services/bcs-client/cmd/list/agent.go
- bcs-services/bcs-client/cmd/list/application.go
- bcs-services/bcs-client/cmd/list/configmap.go
- bcs-services/bcs-client/cmd/list/deployment.go
- bcs-services/bcs-client/cmd/list/endpoint.go
- bcs-services/bcs-client/cmd/list/list.go
- bcs-services/bcs-client/cmd/list/namespace.go
- bcs-services/bcs-client/cmd/list/process.go
- bcs-services/bcs-client/cmd/list/secret.go
- bcs-services/bcs-client/cmd/list/service.go
- bcs-services/bcs-client/cmd/list/taskgroup.go
- bcs-services/bcs-client/cmd/utils/types.go
- bcs-services/bcs-client/cmd/utils/utils.go
- bcs-services/bcs-client/pkg/storage/v1/storage.go
- bcs-services/bcs-client/pkg/storage/v1/types.go
feature:
- client list command support --all-namespaces options
```
OPTIONS:
--all-namespaces, --an         list resources with all namespaces
USAGE:
bcs-client list -t app --all-namespaces
```
> feature: client list command support --all-namespaces options, issue #66

- bcs-k8s/bcs-gamestatefulset-operator/pkg/controllers/game_stateful_set_control.go
- bcs-k8s/bcs-gamestatefulset-operator/pkg/util/canary/canary.go
monotonic control test case:
```shell
[root@kvm-02 ~]# kubectl get po -n wessonli-test -o wide -w
NAME                     READY   STATUS    RESTARTS   AGE     IP           NODE     NOMINATED NODE   READINESS GATES
test-gamestatefulset-2   1/1     Running   1          4m59s   10.42.0.91   kvm-02   <none>           1/1
test-gamestatefulset-1   1/1     Running   1          6m11s   10.42.0.90   kvm-02   <none>           1/1
test-gamestatefulset-0   1/1     Running   1          7m23s   10.42.0.89   kvm-02   <none>           1/1
test-gamestatefulset-2   1/1     Running   1          8m37s   10.42.0.91   kvm-02   <none>           0/1
test-gamestatefulset-2   1/1     Running   1          8m37s   10.42.0.91   kvm-02   <none>           0/1
test-gamestatefulset-2   1/1     Running   1          8m37s …
```
> fix: gamestatefulset rollingUpdate.Partition panic && gamestatefulset monotonic control for updated version replica, not all replica

- bcs-k8s/bcs-gamestatefulset-operator/doc/helm/bcs-gamestatefulset-operator/templates/3-clusterrole.yaml
- bcs-k8s/bcs-hook-operator/pkg/controllers/hook/hook_reconcile.go
- bcs-k8s/bcs-hook-operator/pkg/util/hook/hooks.go
- bcs-k8s/kubernetes/common/bcs-hook/apis/tkex/v1alpha1/hook_types.go
- bcs-k8s/kubernetes/common/bcs-hook/apis/tkex/v1alpha1/zz_generated.deepcopy.go
完成 #766 需求；另解决 “Error limit metric panic” && “gamestatefulset helm template rbac need pod/status” && "代码风格换行“ 3个问题。
> [feature] Hook operator add fast Successful Option

- bcs-k8s/kubebkbcs/apis/bkbcs/v1/bcslogconfig_types.go
> bcslogconfigs 定义添加PodNamePattern字段，以支持logbeat-sidecar的静态pod日志采集需求

- bcs-k8s/bcs-k8s-custom-scheduler/go.mod
- bcs-k8s/bcs-k8s-driver/go.mod
- bcs-k8s/bcs-k8s-watch/go.mod
- bcs-k8s/bcs-kube-agent/go.mod
- bcs-mesos/bcs-scheduler/go.mod
- bcs-mesos/kubebkbcsv2/go.mod
- bcs-network/go.mod
- bcs-services/bcs-alert-manager/go.mod
- bcs-services/bcs-clb-controller/go.mod
- bcs-services/bcs-client/go.mod
- bcs-services/bcs-cluster-manager/go.mod
- bcs-services/bcs-cluster-manager/internal/store/cluster/cluster.go
- bcs-services/bcs-cluster-manager/internal/store/clustercredential/clustercredential.go
- bcs-services/bcs-cluster-manager/internal/store/namespace/namespace.go
- bcs-services/bcs-cluster-manager/internal/store/namespacequota/namespacequota.go
- bcs-services/bcs-cluster-manager/internal/store/tke/tke.go
- bcs-services/bcs-gateway-discovery/go.mod
- bcs-services/bcs-log-manager/go.mod
- bcs-services/bcs-logbeat-sidecar/go.mod
- bcs-services/bcs-mesh-manager/go.mod
- bcs-services/bcs-user-manager/go.mod
- bcs-services/bcs-webhook-server/go.mod
- bmsf-mesh/go.mod
- go.mod
- install/conf/bcs-services/bcs-gateway-discovery/apisix-start.sh
- scripts/env.sh
- 更新各模块所依赖 bcs-common 版本，支持社区无硬编译密码部署
- 按照安全要求删除仓库中的默认密码
> 更新各模块所依赖 bcs-common 版本，支持社区无硬编译密码部署

- bcs-services/bcs-k8s-watch/app/app.go
- bcs-services/bcs-k8s-watch/app/k8s/manager.go
- bcs-services/bcs-k8s-watch/app/k8s/resources/default.go
- bcs-services/bcs-k8s-watch/app/k8s/synchronizer.go
- bcs-services/bcs-k8s-watch/app/k8s/watcher.go
- bcs-services/bcs-k8s-watch/app/options/options.go
- bcs-services/bcs-k8s-watch/go.mod
- install/conf/bcs-services/bcs-k8s-watch/Dockerfile
- install/conf/bcs-services/bcs-k8s-watch/bcs-k8s-watch.json.template
- 增加`watch_resource.namespace`参数，监听指定ns
- 增加`watch_resource.watchDisableNetService`参数，用于设置关闭netservice数据上报
- 增加`watch_resource.watchDisableCrd`，用于设置关闭crd资源的数据上报
- 增加了一个`kubeconfig`参数，方便在容器中监听外部集群
> bcs-k8s-watch: 增加namespace隔离

- bcs-runtime/bcs-k8s/bcs-component/bcs-gamestatefulset-operator/pkg/controllers/game_stateful_set.go
修复 gamestatefulset 对象默认值失效的问题，默认值失效会导致未设置 `spec.updateStrategy.type` 时，不能以 `OnDelete` 策略创建新 Pod。
> fix: enable gamestatefulset scheme default setting

- bcs-runtime/bcs-k8s/kubebkbcs/apis/tkex/v1alpha1/gamestatefulset_types.go
- bcs-runtime/bcs-k8s/kubebkbcs/generated/clientset/versioned/typed/tkex/v1alpha1/fake/fake_gamestatefulset.go
- bcs-runtime/bcs-k8s/kubebkbcs/generated/clientset/versioned/typed/tkex/v1alpha1/gamestatefulset.go
- bcs-runtime/bcs-k8s/kubebkbcs/go.mod
bcs-runtime/bcs-k8s/kubebkbcs依赖的k8s版本升级到0.20.0，与gameworkload保持一致
> 解决bcs-webhook-server的依赖问题

- bcs-runtime/bcs-k8s/bcs-component/bcs-gamedeployment-operator/pkg/controllers/gamedeployment/game_deployment.go
- bcs-runtime/bcs-k8s/bcs-component/bcs-gamestatefulset-operator/pkg/controllers/game_stateful_set.go
1. adopt 操作与 GC 存在竞争，因此 adopt 前需要从 apiserver 获取最新对象，检查 deletionTimestamp: https://github.com/kubernetes/kubernetes/pull/42938；
2. sync 过程的一开始没必要从 apiserver 拿数据，读取 informer 的 cache 即可；
3. create, update, patch, delete 操作需要直接请求 apiserver，这些部分不做修改；
> refactor(GameWorkload): get object info from cache

- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/generator/ruleconverter.go
- bcs-runtime/bcs-k8s/kubernetes/apis/networkextension/v1/ingress_types.go
支持 pod annotation 配置 lb 后端服务权重，需要是直通模式。
annotation 示例：
```
networkextension.bkbcs.tencent.com/clb-weight: "20"
```
配置完成后，会给 pod 添加 annotation `networkextension.bkbcs.tencent.com/clb-weight-ready: "true"`。
> feat: support pod lb weight annotation

- bcs-ui/frontend/src/views/configuration/namespace.vue
fix: 共享集群页面，切换集群时，展示的集群和切换的集群不一致
> fix: 共享集群页面，切换集群时，展示的集群和切换的集群不一致

- bcs-services/bcs-gateway-discovery/plugins/apisix/bcs-dynamic-route.lua
- install/conf/bcs-services/bcs-gateway-discovery/apisix-start.sh
- install/conf/bcs-services/bcs-gateway-discovery/config.yaml.template
关联Issue:
#1491
主要功能：
- 承担gateway-discovery中，原同步cluster credential并生成apisix代理规则的功能
- 抛弃原gateway-discovery为每个集群创建独立路由的做法，以/clusters/*作为唯一入口进行集群请求转发
- 适配以websocket连接集群的请求转发
- 为通过websocket连接的集群在多环境不互通的场景，提供灰度环境转发能力
> BCS 动态路由插件

- bcs-services/bcs-gateway-discovery/plugins/apisix/bcs-auth.lua
> bcs-auth 去除测试注入 port及重定向的urlencode问题

- bcs-runtime/bcs-mesos/bcs-scheduler/src/manager/store/etcd/store.go
- bcs-runtime/bcs-mesos/bcs-scheduler/src/manager/store/zk/store.go
例如 44.44 会取 44.4
44.45 会取 44.5
这个差距不稳定，100个节点极限值：少了 4c，多了 5c
> fix: bcs mesos cluster metrics calc reserve 2 decimal

- docs/features/prometheus/bcs-k8s/bcs-general-pod-autoscaler的监测指标.md
- docs/features/prometheus/grafana/bcs-general-pod-autoscaler.json
- 定义namespace,name,instance变量，可以筛选具体的gpa实例进行查看
- gpa相关报错指标
- gpa副本数，metric模式下cpu和memory相关指标数据
> 为BCS GPA添加 Grafana dashboard

- bcs-common/common/http/httpserver/server.go
- bcs-common/go.mod
Using go-restful-openapi to add swagger2.0.docs.
> feat: add swagger2.0 docs for go-restful server.

- bcs-runtime/bcs-k8s/bcs-network/Makefile
- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/common/common.go
- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/generator/ingressconverter_test.go
- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/portpoolcache/poolcache_test.go
- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/webhookserver/annotationparse_test.go
- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/webhookserver/validate.go
- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/webhookserver/validate_test.go
- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/worker/synchronizer_test.go
- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/portpoolcontroller/portpool.go
- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/portpoolcontroller/portpoolitem.go
- bcs-runtime/bcs-k8s/kubernetes/apis/networkextension/v1/listener_types.go
- bcs-runtime/bcs-k8s/kubernetes/apis/networkextension/v1/portpool_types.go
bcs-ingress-controller 支持 lb 复用，创建和更新 `portpool` 时会由 webhook 检测端口冲突。
> feat: support lb reusable

- bcs-services/bcs-k8s-watch/app/k8s/resources/default.go
- bcs-services/bcs-k8s-watch/app/k8s/watcher.go
- bcs-services/bcs-k8s-watch/app/output/handler.go
- bcs-services/bcs-k8s-watch/app/output/http/client.go
- bcs-services/bcs-k8s-watch/app/output/writer.go
- bcs-services/bcs-k8s-watch/go.mod
- bcs-services/bcs-k8s-watch/main.go
1. increase defaultHandlerQueueSize.
2. directly move data from watchers to handlers.
3. hash event resource to different handlers.
> Performance: watch support large cluster

- bcs-runtime/bcs-mesos/bcs-scheduler/src/manager/sched/offer/offerpool.go
- bcs-runtime/bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/scheduler.go
Mesos Scheduler 由于缺少一个判断错误类型的判断，导致下述 Save AgentSetting 的逻辑无法执行。
> fix: 修复 Mesos Scheduler 不能正常创建 AgentSetting 问题

- bcs-runtime/bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/scheduler.go
- bcs-runtime/bcs-mesos/bcs-scheduler/src/pluginManager/plugin/dynamicPlugin/dynamicPlugin.go
Ref #1833 
测试日志：
```
I0527 10:15:15.986060    9174 scheduler.go:829] get mesos master state: Leader(master@1.88.11.33:5050) Cluster(10000)
E0527 10:15:15.986208    9174 framework.go:43] fail to get framework id, err(store: Not Found)
E0527 10:15:15.986225    9174 scheduler.go:304] fetch framework id from zk failed(ignore the error for now, we'll create it below), err: store: Not Found
I0527 10:15:15.986231    9174 scheduler.go:968] Subscribe with mesos master master@1.88.11.33:5050
I0527 10:15:15.990140    9174 scheduler.go:990] client for mesos master streamID:c9836630-702e-4a6e-b88a-2eb072698b4a
I0527 10:15:15.991348    9174 scheduler.go:1031] subscribe mesos successful with frameworkId 74c98556-f35a-4577-8c5d-1c2b1abb75a9-0001
E0527 10:15:15.991480    9174 framework.go:43] fail to get …
```
> fix: 修复 Mesos 在创建新集群时不能正常写入 framework id #1833

- bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/cmd/gpa/app/default.go
- bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/cmd/gpa/app/options.go
- bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/cmd/gpa/main.go
- bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/pkg/apis/config/v1alpha1/types.go
- bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/pkg/scaler/general.go
- bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/pkg/scaler/general_test.go
Support to set workers, bcs-general-pod-autoscaler can be processed in parallel for workload autoscaling request.
args like this:
```
- args:
- --election-resource-lock=endpoints
- --tlscert=/root/cert.pem
- --tlskey=/root/key.pem
- --general-pod-autoscaler-workers=4
- --v=4
- --port=443
```
> bcs-general-pod-autoscaler support to set workers

- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/httpsvr/httpserver.go
- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/httpsvr/ingress.go
- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/httpsvr/listener.go
- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/httpsvr/portpool.go
- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/httpsvr/util.go
- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/option/option.go
- bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/main.go
通过在 main 函数中创建一个 http.server，暴露出对应的接口，如：
/api/v1/ingress 列表
/api/v1/portpool 列表
/api/v1/listener 列表，根据 ingress/portpool 筛选
-issues:https://github.com/Tencent/bk-bcs/issues/1934
> ingress controller http server
