Tencent/bk-bcs

Makefile
fix: 
- adjust scripts in makefile to avoid errors occurred in sh-based shells
=> fix: adjust scripts in makefile, issue #57

bcs-mesos/bcs-container-executor/app/bcs_executor.go
=> fix: 此方式导致某些情况下executor出现panic的情况，需要去掉check方法; issue #23

scripts/vet.sh
feature:
- add vet.sh in scripts for go vet check
=> feature: add vet.sh for go vet check, issue #65

bcs-services/bcs-dns/plugin/bcsscheduler/cache.go, bcs-services/bcs-dns/plugin/bcsscheduler/lookup.go, bcs-services/bcs-dns/plugin/bcsscheduler/scheduler.go
=> fix: go vet fix, issue #70

Makefile
feature:
- add vet check and fmt in Makefile prework
存量的vet和fmt都已经处理，后续将vet check加入make流程
=> feature: add vet check and fmt in Makefile prework, issue #65

README_en.md
=> English version of BCS translation

bcs-mesos/bcs-container-executor/connection/connection.go, bcs-mesos/bcs-container-executor/executor/executor.go
=> fix: executor与mesos-slave长链接不设置timeout时间; issue #82

install/cmd/conf/bcs-api/config_file.json.template
=> fix: add paas_auth to bcs-api config template. issue #113

bcs-mesos/bcs-container-executor/executor/executor.go
=> fix: 调整executor subcribe时间为1s; issue #82

install/community_edition/service/#etc#bcs#health-master.json
feature：
- 更新health-master配置文件
=> feature: adjust config, issue #0

bcs-services/bcs-api/pkg/models/cluster.go, bcs-services/bcs-api/pkg/models/tke.go, bcs-services/bcs-api/pkg/server/external-cluster/interface.go, bcs-services/bcs-api/pkg/server/external-cluster/tke/tke.go, bcs-services/bcs-api/pkg/server/resthdrs/cluster.go, bcs-services/bcs-api/pkg/server/resthdrs/credentials.go, bcs-services/bcs-api/pkg/server/resthdrs/handlers.go, bcs-services/bcs-api/pkg/server/resthdrs/tke.go, bcs-services/bcs-api/pkg/server/server.go, bcs-services/bcs-api/pkg/storages/sqlstore/tke.go
=> feature: add tke cidr manager. issue #134

bcs-mesos/bcs-consoleproxy/console-proxy/manager/console.go, bcs-services/bcs-api/main.go
=> fix: fix a mistake. issue #152

bcs-common/pkg/module-discovery/mesos-discovery.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/deployment.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/metrics.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/scheduler.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/trans_deleteapp.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/trans_launchapp.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/trans_reschedule.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/trans_scaleapp.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/trans_updateapp.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/transaction.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/update.go, bcs-mesos/bcs-scheduler/src/manager/store/agent.go, bcs-mesos/bcs-scheduler/src/manager/store/application.go, bcs-mesos/bcs-scheduler/src/manager/store/configmap.go, bcs-mesos/bcs-scheduler/src/manager/store/dbzk.go, bcs-mesos/bcs-scheduler/src/manager/store/deployment.go, bcs-mesos/bcs-scheduler/src/manager/store/interface.go, bcs-mesos/bcs-scheduler/src/manager/store/metrics.go, bcs-mesos/bcs-scheduler/src/manager/store/secret.go, bcs-mesos/bcs-scheduler/src/manager/store/service.go, bcs-mesos/bcs-scheduler/src/manager/store/store.go, bcs-mesos/bcs-scheduler/src/types/application.go, bcs-mesos/bcs-scheduler/src/types/metrics.go, bcs-services/bcs-sd-prometheus/app/app.go, bcs-services/bcs-sd-prometheus/app/options/options.go, bcs-services/bcs-sd-prometheus/config/config.go, bcs-services/bcs-sd-prometheus/controller/controller.go, bcs-services/bcs-sd-prometheus/discovery/bcs-mesos-discovery.go, bcs-services/bcs-sd-prometheus/discovery/node-discovery.go, docs/features/prometheus/bcs-sulotion.md
close #168 
close #169 
close #170
=> 1.14.x data sdk

bcs-common/common/conf/types.go, bcs-common/common/types/serverInfo.go, bcs-mesos/bcs-container-executor/executor/executor.go, bcs-mesos/bcs-container-executor/executor/metrics.go, bcs-mesos/bcs-mesos-driver/app/options/options.go, bcs-mesos/bcs-mesos-driver/mesosdriver/config/config.go, bcs-mesos/bcs-mesos-driver/mesosdriver/mesosdriver.go, bcs-mesos/bcs-mesos-watch/app/options.go, bcs-mesos/bcs-mesos-watch/app/watch.go, bcs-mesos/bcs-mesos-watch/main.go, bcs-mesos/bcs-mesos-watch/types/types.go, bcs-services/bcs-api/processor/http/actions/v4http/mesos/mesos-actions.go, bcs-services/bcs-storage/storage/rdiscover/rdiscover.go, docs/features/prometheus/bcs-sulotion.md
=> 1.14.x - bcs mesos支持跨云管理的方案

bcs-services/bcs-storage/storage/drivers/mongodb/watch.go
=> fix: close iter cursor in mongodb server, issue #193

bcs-mesos/bcs-mesos-driver/mesosdriver/backend/v4http/crd.go, bcs-mesos/bcs-mesos-driver/mesosdriver/backend/v4http/scheduler-api.go, bcs-mesos/bcs-scheduler/src/manager/sched/api/api.go, bcs-mesos/bcs-scheduler/src/manager/sched/api/routes.go, bcs-mesos/bcs-scheduler/src/manager/sched/backend/crd.go, bcs-mesos/bcs-scheduler/src/manager/sched/backend/interface.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/scheduler.go, bcs-mesos/bcs-scheduler/src/manager/store/crd.go, bcs-mesos/bcs-scheduler/src/manager/store/interface.go, bcs-mesos/bcs-scheduler/src/manager/store/store.go
=> fix: 修复scheduler启动metrics功能出现的panic问题; issue: #189

bcs-common/pkg/storage/zookeeper/util.go
=> fix: fix mesos-adapter nodewatch init bug, issue #229

bcs-mesos/bcs-scheduler/src/manager/sched/backend/deployment.go
fix:
- deployment-update create a new application for rolling update, but miss the Kind
=> fix: deployment update process error, issue #0

bmsf-mesh/bmsf-mesos-adapter/discovery/bcs/taskgroup.go
… no node ip(pod ip); issue #238
=> fix: fix the bug that missing delete event when delete tas kgroup with no node ip(pod ip); issue #238

bcs-services/bcs-storage/storage/drivers/mongodb/watch.go
fix:
- storage mongodb watching ctx memory leak
=> fix: storage mongodb watching ctx memory leak, issue #0

bcs-services/bcs-storage/storage/actions/v1http/dynamic-mesos/dynamic-action.go, bcs-services/bcs-storage/storage/actions/v1http/dynamic-mesos/utils.go
fix: 
- enable mesos process inspect and list, make sure application and process no conflict, issue #195
=> fix: enable mesos process inspect and list

bcs-mesos/bcs-scheduler/src/manager/store/etcd/application.go, bcs-mesos/bcs-scheduler/src/manager/store/etcd/configmap.go, bcs-mesos/bcs-scheduler/src/manager/store/etcd/deployment.go, bcs-mesos/bcs-scheduler/src/manager/store/etcd/endpoint.go, bcs-mesos/bcs-scheduler/src/manager/store/etcd/secret.go, bcs-mesos/bcs-scheduler/src/manager/store/etcd/service.go, bcs-mesos/bcs-scheduler/src/manager/store/etcd/store.go, bcs-mesos/bcs-scheduler/src/manager/store/etcd/taskgroup.go
=> feature: 过滤掉不合规范的labels #351

bcs-services/bcs-clb-controller/cmd/server.go, bcs-services/bcs-clb-controller/pkg/apis/network/v1/cloudlistener_types.go, bcs-services/bcs-clb-controller/pkg/cloudlb/qcloud/clbDetails.go, bcs-services/bcs-clb-controller/pkg/cloudlb/qcloud/constant.go, bcs-services/bcs-clb-controller/pkg/cloudlb/qcloud/util.go, bcs-services/bcs-clb-controller/pkg/cloudlb/qcloud/util_test.go, bcs-services/bcs-webhook-server/app/app.go, bcs-services/bcs-webhook-server/pkg/inject/common/bscp/bscp.go, bcs-services/bcs-webhook-server/pkg/inject/common/bscp/bscp_test.go, bcs-services/bcs-webhook-server/pkg/inject/k8s/bscp_conf.go, bcs-services/bcs-webhook-server/pkg/inject/k8s_inject.go, bcs-services/bcs-webhook-server/pkg/inject/mesos/bscp_conf.go
fix: fix backends length limitation when use tencentcloud sdk; issue #373
feature: support multiple app configs pulling; #366
support k8s sidecar injection; issue #366
=> fix clb-controller and add k8s bscp sidecar injection

bmsf-configuration/README.md
revise documents about links format.
=> docs: revise documents about links format. issue #443

bcs-mesos/bcs-scheduler/src/manager/store/etcd/store.go, bcs-mesos/bcs-scheduler/src/manager/store/etcd/taskgroup.go
=> feature: 调整kube-apiserver访问的ratelimiter #462

bcs-k8s/bcs-gamestatefulset-operator/go.sum, bcs-k8s/bcs-k8s-watch/app/k8s/synchronizer.go, bcs-k8s/bcs-k8s-watch/app/k8s/watcher.go, docs/version/1.17.x.md, docs/version/1.18.x.md, docs/version/README.md, install/conf/Dockerfile, install/conf/bcs-k8s-master/bcs-cc-agent/Dockerfile, install/conf/bcs-k8s-master/bcs-cc-agent/container-start.sh, install/conf/container-start.sh
=> 1.18.1-alpha

bcs-services/bcs-network/qcloud-eip/conf/conf.go, bcs-services/bcs-network/qcloud-eip/eip/eip.go, bcs-services/bcs-network/qcloud-eip/eip/instance.go, bcs-services/bcs-network/qcloud-eip/eip/netservice.go, bcs-services/bcs-network/qcloud-eip/eip/util.go, bcs-services/bcs-network/qcloud-eip/eip/vpc.go
feature: suppport dynamic scale up in init function #515 
fix: fix problem than eni pod can not communicate with vpc route pod by add ip rule priority; #515
=> 1.17.x qcloud eip fix

bcs-services/bcs-bkcmdb-synchronizer/reconciler/reconciler.go
jump 的 hasher 是非线程安全的, 每次算 hash 时会都是用的同一个变量, 当多个协程同时使用时会产生竞争. 
而 transferLoop 和 fullSyncLoop 两个协程都引用了同一个 hasher.
=> fixes data race on reconciler

bcs-mesos/bcs-scheduler/src/manager/sched/api/api.go, bcs-mesos/bcs-scheduler/src/manager/sched/api/routes.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/bcs_event.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/daemonset.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/data_check.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/deployment.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/healthy_msg.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/message.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/scheduler.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/service_mgr.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/task_operate.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/trans_command.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/trans_deleteapp.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/trans_launchapp.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/trans_reschedule.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/trans_scaleapp.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/trans_updateapp.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/trans_updateapp_resource.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/transaction.go, bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/update.go, bcs-mesos/bcs-scheduler/src/manager/sched/task/executor.go, bcs-mesos/bcs-scheduler/src/manager/sched/task/resources.go, bcs-mesos/bcs-scheduler/src/manager/sched/task/task.go, bcs-mesos/bcs-scheduler/src/manager/store/etcd/deployment.go
* 修复bcs-scheduler etcd模式下taskgroup脏数据问题
* 修复gometalinter告警
=> bcs-scheduler脏数据问题 & gometalinter

bcs-network/bcs-ingress-controller/internal/cloud/tencentcloud/helper.go, bcs-network/bcs-ingress-controller/internal/cloud/tencentcloud/util.go
fix: fix update listener attr lost lb id;
fix: fix sessionExpire close problem;
fix: fix update rule attr;
=> fix update listener and rule attr

bcs-k8s/bcs-gamedeployment-operator/doc/deploy/01-resources.yaml, bcs-k8s/bcs-gamedeployment-operator/pkg/apis/tkex/v1alpha1/types.go, bcs-k8s/bcs-gamestatefulset-operator/doc/deploy/01-resources.yaml, bcs-k8s/bcs-gamestatefulset-operator/doc/example/gamestatefulset-sample.yaml, bcs-k8s/bcs-gamestatefulset-operator/pkg/apis/tkex/v1alpha1/types.go, bcs-k8s/kubernetes/common/bcs-hook/apis/tkex/v1alpha1/hook_types.go
=> Fix crd validation

bcs-services/bcs-webhook-server/internal/plugin/dbprivilege/dbprivilege.go, bcs-services/bcs-webhook-server/pkg/apis/bk-bcs/v1/db_priv_config.go
=> db授权支持配置operator

bmsf-configuration/internal/protocol/apiserver/Makefile, bmsf-configuration/internal/protocol/authserver/Makefile, bmsf-configuration/internal/protocol/bcs-controller/Makefile, bmsf-configuration/internal/protocol/common/Makefile, bmsf-configuration/internal/protocol/configserver/Makefile, bmsf-configuration/internal/protocol/connserver/Makefile, bmsf-configuration/internal/protocol/datamanager/Makefile, bmsf-configuration/internal/protocol/gse-controller/Makefile, bmsf-configuration/internal/protocol/sidecar/Makefile, bmsf-configuration/internal/protocol/templateserver/Makefile, bmsf-configuration/internal/protocol/tunnelserver/Makefile, bmsf-configuration/internal/strategy/strategy.go
fix bmsf-configuration bscp empty strategy values bug;
change protocol abs paths config in makefile;
=> bugfix: fix bmsf-configuration bscp empty strategy values bug. issue #782

bcs-common/pkg/esb/client/client.go, bcs-common/pkg/esb/client/request.go, bcs-common/pkg/odm/drivers/db.go, bcs-common/pkg/odm/drivers/mongo/mongo.go
feature: db driver interface support aggregation query; issue #792
fix: change metric label from subpath to method; issue #791
=> feature: db driver interface support aggregation query; issue #792

bcs-common/pkg/esb/client/client.go, bcs-common/pkg/esb/client/request.go
=> bcs-common/pkg/esb/client 支持自定义transport和随机访问endpoints

bcs-services/bcs-logbeat-sidecar/sidecar/cache.go, bcs-services/bcs-logbeat-sidecar/sidecar/controller.go
=> Fix logbeat sidecar container stopped without destroy event

bcs-services/bcs-clb-controller/go.mod, bcs-services/bcs-logbeat-sidecar/go.mod, bcs-services/bcs-logbeat-sidecar/sidecar/controller.go, bcs-services/bcs-logbeat-sidecar/sidecar/logconfig.go, go.mod
=> [logbeat-sidecar] static pod log collection

bcs-k8s/bcs-k8s-driver/Makefile, bcs-network/Makefile, bcs-services/bcs-cluster-manager/Makefile
=> makefile更新

bcs-services/bcs-logbeat-sidecar/app/app.go, bcs-services/bcs-logbeat-sidecar/app/options/options.go, bcs-services/bcs-logbeat-sidecar/config/config.go, bcs-services/bcs-logbeat-sidecar/sidecar/controller.go, bcs-services/bcs-logbeat-sidecar/sidecar/logconfop_linux.go, bcs-services/bcs-logbeat-sidecar/types/types.go
=> bkunifylogbeat 适配

bcs-common/go.mod, bcs-common/pkg/bcsapi/client.go, bcs-common/pkg/bcsapi/storage.go, bcs-common/pkg/bcsapi/storage/common.go, bcs-common/pkg/bcsapi/storage/pod.go, bcs-common/pkg/odm/drivers/db.go, bcs-common/pkg/odm/drivers/mongo/mongo.go
=> storage client etcd服务发现 && mongo-driver 1.5版本插入索引报错

docs/install/source_compile.md
=> update source_compile.md doc

docs/features/bcs-gamestatefulset-operator/inPlaceUpdate.md
=> fix doc: gamestatefulset inPlaceUpdate example error

bcs-k8s/kubebkbcs/apis/bkbcs/v1/bcslogconfig_types.go, bcs-services/bcs-alert-manager/pkg/consumer/consumer_test.go, bcs-services/bcs-storage/storage/actions/v1http/dynamic/dynamic.go, bcs-services/bcs-storage/storage/store/mongo/mongo_test.go, bcs-services/bcs-storage/storage/watchbus/dispatcher_test.go, docs/features/bcs-api-gateway/api-gateway方案.md, docs/features/bcs-cloud-network/operationguide/ops-guide.md
=> bcslogconfig CRD 字段修改，以支持multiline配置，以及日志配置生命周期优化

bcs-common/common/encrypt/des.go, bcs-network/bcs-networkpolicy/controller/controller.go, bcs-network/bcs-networkpolicy/controller/networkpolicy/controller.go
=> bcs-common/common/encrypt 支持不加密

bcs-k8s/bcs-gamedeployment-operator/pkg/scale/gamedeployment_scale.go, bcs-k8s/bcs-gamedeployment-operator/pkg/update/gamedeployment_update.go, bcs-k8s/kubernetes/common/bcs-hook/predelete/predelete.go, bcs-k8s/kubernetes/common/bcs-hook/preinplace/preinplace.go
filter out not running pods when CheckDelete and CheckInplace
=> fix(bcs-hook): filter out not running pods

bcs-ui/backend/container_service/observability/metric/views/cluster.py
=> minor: ignore no node error when query cluster metric

bcs-ui/frontend/.eslintrc.js, bcs-ui/frontend/build/prod.env.js, bcs-ui/frontend/package.json, bcs-ui/frontend/src/api/request.js, bcs-ui/frontend/src/main.js, bcs-ui/frontend/src/router/index.js, bcs-ui/frontend/src/views/depot/project-image.vue, bcs-ui/frontend/src/views/helm/app-detail.vue, bcs-ui/frontend/src/views/helm/index.vue, bcs-ui/frontend/src/views/helm/tpl-instance.vue
=> fix: 查看资源详情跳转链接问题

bcs-ui/backend/helm/app/urls.py, bcs-ui/backend/helm/app/utils.py, bcs-ui/backend/helm/app/views.py
=> feat: 调整路径

bcs-ui/frontend/src/views/depot/image-library.vue, bcs-ui/frontend/src/views/depot/project-image.vue
=> fix: 去除推镜像白皮书链接

bcs-ui/frontend/src/views/navigation.vue
=> fix: 修复百分浏览器ICON放大问题

bcs-ui/frontend/src/views/index.vue
=> 导航记录用户上一次的项目信息

bcs-ui/frontend/src/views/index.vue
=> feat: 导航记录用户上一次的项目信息

bcs-ui/frontend/src/views/cluster/create.vue
=> fix: 创建集群失败后，保留在当前页面

bcs-ui/frontend/src/App.vue, bcs-ui/frontend/src/views/index.vue
=> optimization: 优化项目缓存上一次项目逻辑

bcs-ui/frontend/src/css/app.css, bcs-ui/frontend/src/views/cluster/mixin-node.js, bcs-ui/frontend/src/views/cluster/node.vue
1. 导航【节点】和【节点添加】页面接口统一
2.  ace编辑器滚动条样式调整
=> 导航【节点】和【节点添加】页面接口统一 || ace编辑器滚动条样式调整

bcs-network/bcs-ingress-controller/internal/cloud/tencentcloud/sdk.go, bcs-network/bcs-ingress-controller/internal/webhookserver/mutating.go, bcs-network/bcs-ingress-controller/internal/webhookserver/utils.go, bcs-network/bcs-ingress-controller/portbindingcontroller/podfilter.go, bcs-network/bcs-ingress-controller/portbindingcontroller/portbindingcontroller.go, bcs-network/bcs-ingress-controller/portbindingcontroller/portbindingitem.go, bcs-network/bcs-ingress-controller/portbindingcontroller/util.go
fix: fix the portbinding create error when pod is recreated in very short time; issue #1006
=> fix the portbinding create error when pod is recreated in very short time

bcs-ui/backend/container_service/clusters/tools/node.py
=> feat: update node status exception

bcs-ui/frontend/src/components/tip-dialog/index.css, bcs-ui/frontend/src/components/tip-dialog/index.vue, bcs-ui/frontend/src/i18n/lang.js, bcs-ui/frontend/src/views/cluster/mixin-node.js, bcs-ui/frontend/src/views/cluster/node.vue
=> fix: 节点管理页面添加节点页增加提示

bcs-ui/backend/container_service/clusters/tools/node.py, bcs-ui/backend/resources/client.py, bcs-ui/backend/settings/base.py, bcs-ui/backend/tests/resources/test_client.py, bcs-ui/backend/utils/whitelist.py
=> feat: 正式环境集群开放访问新版bcs api

bcs-ui/frontend/src/views/node/index.vue
=> 节点管理页选中节点，轮询后选中结果失效问题

.gitignore, bcs-ui/frontend/.eslintrc.js, bcs-ui/frontend/index-dev.html, bcs-ui/frontend/index.html, bcs-ui/frontend/package.json, bcs-ui/frontend/src/components/ip-selector/ip-selector-bcs.vue, bcs-ui/frontend/src/views/cluster/create.external.vue, bcs-ui/frontend/src/views/cluster/info.vue, bcs-ui/frontend/src/views/navigation.vue
=> fix:  私有化版本问题修复

bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/cloud/tencentcloud/sdk.go, bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/webhookserver/mutating.go, bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/webhookserver/utils.go, bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/portbindingcontroller/podfilter.go, bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/portbindingcontroller/portbindingcontroller.go, bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/portbindingcontroller/portbindingitem.go, bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/portbindingcontroller/util.go
fix the portbinding create error when pod is recreated in very shortime, merge from#1007 manually
=> fix the portbinding create error when pod is recreated in very shortime, merge from#1007 manually

bcs-ui/frontend/src/views/dashboard/resource-update/resource-editor.vue
=> feat: 资源视图编辑器组件支持忽略某些diff字段

bcs-ui/frontend/src/components/cluster-selector/index.vue, bcs-ui/frontend/src/css/app.css, bcs-ui/frontend/src/store/modules/cluster.js, bcs-ui/frontend/src/views/cluster/index.vue, bcs-ui/frontend/src/views/configuration/namespace.vue, bcs-ui/frontend/src/views/helm/index.vue, bcs-ui/frontend/src/views/mc/event-query.vue, bcs-ui/frontend/src/views/metric/main.vue, bcs-ui/frontend/src/views/navigation.vue, bcs-ui/frontend/src/views/node/index.vue, bcs-ui/frontend/src/views/side-nav.vue, bcs-ui/frontend/src/views/storage/pv.vue, bcs-ui/frontend/src/views/storage/pvc.vue, bcs-ui/frontend/src/views/storage/storage-class.vue
=> feta: 公共集群调整

bcs-ui/frontend/src/api/base.js, bcs-ui/frontend/src/components/bk-magic-2.0/bk-popover.js, bcs-ui/frontend/src/store/index.js, bcs-ui/frontend/src/store/modules/dashboard.js, bcs-ui/frontend/src/views/dashboard/common/base-layout.tsx, bcs-ui/frontend/src/views/dashboard/common/use-namespace.ts, bcs-ui/frontend/src/views/dashboard/common/use-subscribe.ts, bcs-ui/frontend/src/views/dashboard/common/use-table-data.ts, bcs-ui/frontend/src/views/dashboard/resource-update/resource-update.vue
=> feat: 资源视图 & 命名空间优化

bcs-ui/frontend/src/components/cluster-selector/index.vue, bcs-ui/frontend/src/components/terminal/index.vue, bcs-ui/frontend/src/store/index.js, bcs-ui/frontend/src/store/modules/cluster.js, bcs-ui/frontend/src/views/cluster/index.vue, bcs-ui/frontend/src/views/configuration/instantiation.vue, bcs-ui/frontend/src/views/configuration/namespace.vue, bcs-ui/frontend/src/views/configuration/templateset.vue, bcs-ui/frontend/src/views/helm/index.vue, bcs-ui/frontend/src/views/helm/tpl-instance.vue, bcs-ui/frontend/src/views/hpa/index.vue, bcs-ui/frontend/src/views/index.vue, bcs-ui/frontend/src/views/mc/event-query.vue, bcs-ui/frontend/src/views/metric/main.vue, bcs-ui/frontend/src/views/navigation.vue, bcs-ui/frontend/src/views/network/loadbalance/k8s/index.vue, bcs-ui/frontend/src/views/network/service/k8s.vue, bcs-ui/frontend/src/views/network/service/mixin.js, bcs-ui/frontend/src/views/node/index.vue, bcs-ui/frontend/src/views/resource/configmap.vue, bcs-ui/frontend/src/views/resource/ingress/k8s/index.vue, bcs-ui/frontend/src/views/resource/secret.vue, bcs-ui/frontend/src/views/side-nav.vue, bcs-ui/frontend/src/views/storage/pv.vue, bcs-ui/frontend/src/views/storage/pvc.vue, bcs-ui/frontend/src/views/storage/storage-class.vue
=> feat: 公共集群调整

bcs-ui/frontend/src/store/index.js
=> fix: 公共集群获取菜单接口调整

bcs-ui/frontend/src/views/cluster/mixin-node.js
=> fix: 节点管理搜索查询过滤多个ip匹配错误问题修复

bcs-ui/frontend/src/store/index.js, bcs-ui/frontend/src/store/modules/cluster.js, bcs-ui/frontend/src/views/cluster/index.vue, bcs-ui/frontend/src/views/cluster/use-cluster.ts, bcs-ui/frontend/src/views/configuration/instantiation.vue, bcs-ui/frontend/src/views/configuration/namespace.vue, bcs-ui/frontend/src/views/helm/tpl-instance.vue, bcs-ui/frontend/src/views/index.vue, bcs-ui/frontend/src/views/mc/event-query.vue, bcs-ui/frontend/src/views/metric/main.vue, bcs-ui/frontend/src/views/node/index.vue, bcs-ui/frontend/src/views/storage/pv.vue, bcs-ui/frontend/src/views/storage/pvc.vue, bcs-ui/frontend/src/views/storage/storage-class.vue
=> fix: featureflag和共享集群字段修改

bcs-ui/backend/container_service/misc/bke_client/constants.py, bcs-ui/backend/settings/base.py, bcs-ui/backend/settings/ce/base.py
=> feat: 添加kubectl版本

bcs-ui/frontend/src/views/mc/event-query.vue, bcs-ui/frontend/src/views/metric/main.vue, bcs-ui/frontend/src/views/storage/pv.vue, bcs-ui/frontend/src/views/storage/pvc.vue, bcs-ui/frontend/src/views/storage/storage-class.vue
=> fix: 修复删除全部集群选项后界面下拉组件问题

bcs-ui/frontend/src/App.vue, bcs-ui/frontend/src/common/constant.ts, bcs-ui/frontend/src/common/use-gohome.ts, bcs-ui/frontend/src/components/cluster-selector/index.vue, bcs-ui/frontend/src/components/terminal/index.vue, bcs-ui/frontend/src/css/app.css, bcs-ui/frontend/src/i18n/lang.js, bcs-ui/frontend/src/store/modules/cluster.js, bcs-ui/frontend/src/views/configuration/instantiation.vue, bcs-ui/frontend/src/views/configuration/namespace.vue, bcs-ui/frontend/src/views/dashboard/common/base-layout.tsx, bcs-ui/frontend/src/views/dashboard/common/use-namespace.ts, bcs-ui/frontend/src/views/dashboard/common/use-table-data.ts, bcs-ui/frontend/src/views/dashboard/resource-update/resource-update.vue, bcs-ui/frontend/src/views/dashboard/workload/detail/pod-detail.vue, bcs-ui/frontend/src/views/helm/index.vue, bcs-ui/frontend/src/views/index.vue, bcs-ui/frontend/src/views/navigation.vue, bcs-ui/frontend/src/views/side-nav.vue, bcs-ui/frontend/src/views/variable/index.vue
=> optimization: 公共集集群优化

bcs-ui/frontend/src/views/configuration/instantiation.vue, bcs-ui/frontend/src/views/configuration/namespace.css, bcs-ui/frontend/src/views/configuration/namespace.vue, bcs-ui/frontend/src/views/dashboard/workload/detail/pod-log.css, bcs-ui/frontend/src/views/dashboard/workload/detail/use-log.ts, bcs-ui/frontend/src/views/dashboard/workload/detail/workload-detail.vue, bcs-ui/frontend/src/views/dashboard/workload/pods.vue
fix: 公共集群体验问题修复 & 资源视图pods新增日志
=> fix: 公共集群体验问题修复 & 资源视图pods新增日志

bcs-ui/frontend/src/views/dashboard/workload/detail/use-log.ts
=> fix: 修复pods列表日志组件数据缓存问题

bcs-ui/frontend/src/api/base.js, bcs-ui/frontend/src/api/request.js, bcs-ui/frontend/src/components/terminal/index.vue, bcs-ui/frontend/src/css/app.css, bcs-ui/frontend/src/i18n/lang.js, bcs-ui/frontend/src/router/cluster.js, bcs-ui/frontend/src/store/index.js, bcs-ui/frontend/src/store/modules/cluster.js, bcs-ui/frontend/src/store/modules/clustermanager.js, bcs-ui/frontend/src/views/cluster/create-cluster/create-cluster.vue, bcs-ui/frontend/src/views/cluster/create-cluster/create-form-cluster.vue, bcs-ui/frontend/src/views/cluster/create-cluster/create-import-cluster.vue, bcs-ui/frontend/src/views/cluster/create-cluster/form-group.vue, bcs-ui/frontend/src/views/cluster/create-cluster/form-mode.vue, bcs-ui/frontend/src/views/cluster/index.vue, bcs-ui/frontend/src/views/cluster/info.vue, bcs-ui/frontend/src/views/cluster/mixin-node.js, bcs-ui/frontend/src/views/cluster/overview.vue, bcs-ui/frontend/src/views/cluster/use-cluster.ts, bcs-ui/frontend/src/views/content-header.vue, bcs-ui/frontend/src/views/dashboard/common/status-icon.tsx, bcs-ui/frontend/src/views/index.vue
=> feat: 集群管理前端UI

bcs-ui/backend/components/proxy.py, bcs-ui/backend/container_service/clusters/mgr/proxy/urls.py, bcs-ui/backend/container_service/clusters/mgr/proxy/views.py, bcs-ui/backend/settings/base.py, bcs-ui/backend/tests/components/test_proxy.py, bcs-ui/backend/urls.py
=> docs: 添加 cluster manager 代理，转发请求到cluster manager服务

bcs-ui/frontend/src/views/cluster/mixin-node.js
=> fix: 节点管理有过滤条件时，允许停止调度时过滤失败修复

bcs-ui/frontend/src/views/dashboard/namespace.tsx, bcs-ui/frontend/src/views/helm/index.vue, bcs-ui/frontend/src/views/side-nav.vue
=> fix: 修复release列表轮询问题 & 命名空间轮询

bcs-ui/frontend/src/common/use-gohome.ts
=> optimization: 优化跳转首页判断

bcs-ui/frontend/src/App.vue, bcs-ui/frontend/src/components/shared-cluster-tips/index.vue, bcs-ui/frontend/src/views/configuration/namespace.vue, bcs-ui/frontend/src/views/navigation.vue
=> feat: 共享集群提示框

bcs-ui/frontend/src/views/helm/tpl-instance.vue
=> fix: 修复chart部署遮罩样式问题

bcs-ui/backend/container_service/clusters/views/node_views/nodes.py
通过clustermanager查询节点处于未加入集群时的状态，方便用户重试等操作
=> feat: 通过clustermanager获取节点状态

bcs-ui/backend/bcs_web/middleware.py, bcs-ui/backend/settings/base.py, bcs-ui/backend/settings/ce/base.py, bcs-ui/backend/settings/ce/dev.py, bcs-ui/backend/settings/ce/saas_prod.py, bcs-ui/backend/tests/bcs_web/test_middleware.py, bcs-ui/backend/utils/views.py
=> feat: support multi cookie domains

bcs-ui/frontend/src/api/index.js, bcs-ui/frontend/src/components/file-upload/index.vue
minor: backend_csrftoken -> bcs_csrftoken
=> minor: backend_csrftoken -> bcs_csrftoken

bcs-ui/frontend/src/views/app/k8s/tmpl-instance.html
minor: 删除deployment metric信息展示
=> minor: 删除deployment metric信息展示

bcs-runtime/bcs-k8s/bcs-component/bcs-gamestatefulset-operator/pkg/controllers/game_stateful_set_utils.go
=> fix(bcs-gamestatefulset): fix newVersionedGameStatefulSetPod

bcs-ui/frontend/src/components/ip-selector/ip-selector-bcs.vue, bcs-ui/frontend/src/views/cluster/mixin-node.js
optimization: 去除is_used逻辑 & 添加节点权限修改为used
=> optimization: 去除is_used逻辑 & 添加节点权限修改为used

bcs-ui/frontend/src/views/app/mixins/mixin-base-instantiation.js
=> fix: 修复应用模板集实例化后没有跳回列表问题

bcs-ui/frontend/src/store/modules/cluster.js, bcs-ui/frontend/src/views/cluster/mixin-node.js
=> fix: 节点管理复制全部IP修复

docs/features/prometheus/grafana/bcs-gamedeployment-operator.json, docs/features/prometheus/grafana/bcs-gamedeployment.json, docs/features/prometheus/grafana/bcs-gamestatefulset, docs/features/prometheus/grafana/bcs-gamestatefulset-operator.json, docs/features/prometheus/grafana/bcs-hook-operator.json
1. 调整 operator  dashboard 视图；
2. 增加 GameDeployment/GameStatefulset dashboard；
=> feature(GameWorkload): adjust Dashboard

bcs-ui/frontend/src/views/node/index.vue
=> fix: 外部节点菜单复选框功能缺陷修复

bcs-ui/frontend/src/api/index.js, bcs-ui/frontend/src/components/apply-perm/index.vue, bcs-ui/frontend/src/views/configuration/namespace.vue
=> feat: 权限中心v3联调

bcs-ui/frontend/src/api/index.js, bcs-ui/frontend/src/components/apply-perm/index.vue, bcs-ui/frontend/src/views/configuration/instantiation.vue, bcs-ui/frontend/src/views/configuration/templateset.vue
=> feat: 模板集权限对接V3

bcs-ui/frontend/src/views/cluster/apply-host.vue
=> fix: 申请服务器弹框样式调整

bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/pkg/scaler/general.go
修复 GPA 实例指定数据源出错时会导致 GPA 组件崩溃 的情况
=> fix(general-pod-autoscaler): fix error assignment

bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/constant/constant.go, bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/generator/ingressconverter.go, bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/generator/util.go, bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/internal/worker/synchronizer.go
add: check liId and lbname more strictly
=> add: check lbId and lbname more strictly

bcs-ui/frontend/src/views/node/node.vue
=> 节点管理标签、污点增加tips

bcs-common/pkg/otel/metric/example/prometheus/main.go, bcs-common/pkg/otel/metric/metric.go, bcs-common/pkg/otel/metric/options.go, bcs-common/pkg/otel/metric/prometheus/provider.go
=> 封装openTelemetry metric

bcs-ui/frontend/src/views/configuration/k8s-create/yaml-mode/index.css
=> feat: 新增yaml模板集样式缺陷修复

bcs-runtime/bcs-k8s/kubebkbcs/apis/bkbcs/v1/bcsdbprivconfig_types.go
=> 【前置依赖】DB授权CRD支持CDP_GCS

bcs-runtime/bcs-k8s/bcs-component/bcs-gamedeployment-operator/cmd/gamedeployment-operator/main.go, bcs-runtime/bcs-k8s/bcs-component/bcs-gamedeployment-operator/go.mod, bcs-runtime/bcs-k8s/bcs-component/bcs-gamedeployment-operator/pkg/controllers/gamedeployment/game_deployment.go, bcs-runtime/bcs-k8s/bcs-component/bcs-gamedeployment-operator/pkg/metrics/metrics.go, bcs-runtime/bcs-k8s/bcs-component/bcs-gamestatefulset-operator/cmd/gamestatefulset-operator/main.go, bcs-runtime/bcs-k8s/bcs-component/bcs-gamestatefulset-operator/go.mod, bcs-runtime/bcs-k8s/bcs-component/bcs-gamestatefulset-operator/pkg/controllers/game_stateful_set.go, bcs-runtime/bcs-k8s/bcs-component/bcs-gamestatefulset-operator/pkg/controllers/metrics.go, bcs-runtime/bcs-k8s/bcs-component/bcs-hook-operator/cmd/hook-operator/main.go, bcs-runtime/bcs-k8s/bcs-component/bcs-hook-operator/go.mod, bcs-runtime/bcs-k8s/bcs-component/bcs-hook-operator/pkg/controllers/hook/hook.go, bcs-runtime/bcs-k8s/bcs-component/bcs-hook-operator/pkg/controllers/hook/metrics.go
1. 包括 operator pod 和 crd 版本
2. 记录在 label 中
=> feature(gameworkload): expose version info via prometheus

bcs-services/bcs-webconsole/console/api/service.go, bcs-services/bcs-webconsole/i18n/constant.go, bcs-services/bcs-webconsole/i18n/gin_context.go, bcs-services/bcs-webconsole/main.go, bcs-services/bcs-webconsole/route/middleware.go
=> feature: webconsole i18n未初始化

bcs-services/bcs-k8s-watch/app/k8s/watcher.go
=> fix: bcs-k8s-watch memory leak.

bcs-ui/frontend/src/store/modules/cluster.js, bcs-ui/frontend/src/views/cluster/info.vue, bcs-ui/frontend/src/views/resource/ingress/k8s/index.vue
=> fix: 获取Ingress列表接口未携带集群ID问题

bcs-ui/frontend/src/views/metric/searcher.vue, bcs-ui/frontend/src/views/storage/pv.vue
=> fix: 切换页面后，缓存的集群和页面展示的集群数据不一致

bcs-common/go.mod, bcs-common/pkg/bcsmonitor/client.go, bcs-common/pkg/bcsmonitor/client_test.go, bcs-common/pkg/bcsmonitor/types.go
=> feature: add bcs monitor client

bcs-services/bcs-webconsole/console/config/base.go, bcs-services/bcs-webconsole/console/web/templates/mgr.html, bcs-services/bcs-webconsole/etc/config.yaml, bcs-services/bcs-webconsole/i18n/constant.go, bcs-services/bcs-webconsole/i18n/gin_context.go, bcs-services/bcs-webconsole/i18n/gin_i18n.go, bcs-services/bcs-webconsole/i18n/i18n.go
- 修正配置文件中language_code参数拼写错误
- 从配置文件中设置默认语言
- 多语言匹配改进
- 兼容对x/text/language语言匹配器的改进
#1393
=> [feature] bcs-webconsole 多语言匹配改进

bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/pkg/apis/autoscaling/register.go, bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/pkg/apis/autoscaling/v1alpha1/types.go, bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/pkg/scaler/general.go, bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/pkg/validation/validation.go
1. 兼容所有模式，取各模式下的最大值为推荐值；
2. 修复验证机制错误
3. 增加 kubebuilder 标记，便于生成 CRD
=> fix(gpa): GPA compatible

bcs-services/bcs-argocd-manager/charts/build.sh, bcs-services/bcs-argocd-manager/go.mod, bcs-services/bcs-argocd-manager/images/build.sh, bcs-services/bcs-argocd-manager/main.go, bcs-services/bcs-argocd-manager/plugins/repo-sidecar/main.go
=> feature: enable bcs-argocd-manager, issue: #1438

bcs-runtime/bcs-k8s/kubernetes/common/bcs-hook/apis/tkex/v1alpha1/hook_types.go, bcs-runtime/bcs-k8s/kubernetes/common/util/hook/hook.go
给 hook type 增加 Policy 字段，为执行策略指定（串行/并行）作准备
=> feature(hook): add Policy field in hook type

bcs-ui/frontend/src/store/modules/cluster.js, bcs-ui/frontend/src/views/node/node.vue, bcs-ui/frontend/src/views/node/use-node.ts
=> fix: 节点管理允许、停止调度接口调整

bcs-ui/frontend/src/views/crdcontroller/polaris_list.vue
=> fix: Polaris信息名前端校验增加特殊符号冒号

bcs-ui/frontend/src/store/modules/cluster.js, bcs-ui/frontend/src/views/node/node.vue, bcs-ui/frontend/src/views/node/use-node.ts
=> reset commit

bcs-runtime/bcs-mesos/bcs-scheduler/src/manager/store/etcd/store.go, bcs-runtime/bcs-mesos/bcs-scheduler/src/manager/store/metrics.go, bcs-runtime/bcs-mesos/bcs-scheduler/src/manager/store/zk/store.go
修改 Mesos 集群 Cluster 剩余资源计算方式，增加 cluster_cpu/mem_available，此指标排除 disable 节点
=> feature: change mesos cluster resource metric, add cluster_cpu/mem_available

bcs-runtime/bcs-k8s/bcs-component/bcs-webhook-server/go.mod, bcs-runtime/bcs-k8s/bcs-component/bcs-webhook-server/internal/plugin/bcslog/bcslog.go, bcs-runtime/bcs-k8s/bcs-component/bcs-webhook-server/internal/plugin/bcslog/bcslogmesos.go, bcs-runtime/bcs-k8s/bcs-component/bcs-webhook-server/internal/plugin/bcslog/types.go, bcs-runtime/bcs-k8s/bcs-component/bcs-webhook-server/internal/plugin/dbprivilege/dbprivilege.go, bcs-runtime/bcs-k8s/bcs-component/bcs-webhook-server/internal/plugin/dbprivilege/options.go, bcs-runtime/bcs-k8s/bcs-component/bcs-webhook-server/internal/plugin/imageloader/bcsgd.go, bcs-runtime/bcs-k8s/bcs-component/bcs-webhook-server/internal/plugin/imageloader/bcsgs.go, bcs-runtime/bcs-k8s/bcs-component/bcs-webhook-server/internal/plugin/imageloader/job.go
=> db授权支持CDP GCS

bcs-ui/frontend/src/store/modules/k8s-template.js, bcs-ui/frontend/src/views/configuration/k8s-create/ingress.vue, bcs-ui/frontend/src/views/configuration/k8s-create/ingress/ce/k8s-ingress.vue, bcs-ui/frontend/src/views/ingress/k8s-ingress.vue, bcs-ui/frontend/src/views/resource/ingress/k8s/index.vue
fix: 去掉模板集中ingress关联证书的自动关联|前端去掉关联
=> fix: 去掉模板集中ingress关联证书的自动关联|前端去掉关联

bcs-ui/frontend/src/views/configuration/namespace.vue, bcs-ui/frontend/src/views/helm/tpl-list.vue
feat: 【优化】删除chart版本，可以支持shift选择多版本
=> feat: 【优化】删除chart版本，可以支持shift选择多版本

bcs-services/bcs-user-manager/app/user-manager/store.go
=> fix: sync token to redis

docs/features/opentelemetry/Helm部署Jaeger.md, docs/features/opentelemetry/opentelemetry接入规范.md
添加OpenTelemetry接入规范和Helm部署Jaeger教程
=> 添加OpenTelemetry接入规范和Helm部署Jaeger教程

bcs-ui/frontend/src/router/crdcontroller.js, bcs-ui/frontend/src/store/modules/crdcontroller.js, bcs-ui/frontend/src/views/crdcontroller/detail.vue, bcs-ui/frontend/src/views/crdcontroller/index.vue
=> feat: 组件库支持用户升级

bcs-services/bcs-k8s-watch/app/k8s/synchronizer.go, bcs-services/bcs-k8s-watch/app/output/http/client.go
=> fix: bcs k8s watch sync event duplicate

bcs-services/bcs-storage/storage/clean/cleaner.go
=> fix: cleaner with maxEntryNum.

bcs-services/bcs-storage/storage/actions/v1http/events/events-action.go, bcs-services/bcs-storage/storage/actions/v1http/events/utils.go
=> feat: split event table by cluster.

bcs-services/bcs-webconsole/console/api/service.go, bcs-services/bcs-webconsole/console/api/websocket.go, bcs-services/bcs-webconsole/console/manager/conn.go, bcs-services/bcs-webconsole/console/manager/constants.go, bcs-services/bcs-webconsole/console/manager/manager.go, bcs-services/bcs-webconsole/console/podmanager/startup.go, bcs-services/bcs-webconsole/console/web/templates/index.html, bcs-services/bcs-webconsole/go.mod, bcs-services/bcs-webconsole/go.sum, bcs-services/bcs-webconsole/route/permissions.go
Fix: openapi 正常command命令
Fix: exit命令导致服务卡死问题
Fix: 容器正常，即可登入webconsole
=> Improve: conn send PreparedGuideMessage when had bcs api first byte

bcs-runtime/bcs-k8s/kubernetes/common/update/inplaceupdate/inplace_update.go
1. 原先会修改 condition 中的 InplaceUpdateReady 和 Ready，但 Ready 状态本应由 kubelet 计算得到，因此两者会发生冲突，导致原地更新过程中，更新完成后，Ready 会重新被设置成 False 的情况，从而出现服务中断。
2. 原地更新过程中，顺序发生：Ready: False(开始更新, kubelet 根据 readinessgate 更新为 False) -> Ready: True(更新完成，operator更新 Ready 为True）-> Ready: False(kubelet 重新修改为False) -> Ready: True(kubelet 修改为True)
3. 应该去掉修改 Ready 的逻辑，让 kubelet 完成这部分工作
=> fix(inplace): only change readiness gate condition when inplace update

bcs-services/bcs-k8s-watch/app/k8s/manager.go, bcs-services/bcs-k8s-watch/app/k8s/synchronizer.go, bcs-services/bcs-k8s-watch/app/output/http/client.go, bcs-services/bcs-storage/storage/actions/lib/store.go, bcs-services/bcs-storage/storage/actions/v1http/dynamic/dynamic.go, bcs-services/bcs-storage/storage/actions/v1http/events/events-action.go, bcs-services/bcs-storage/storage/actions/v1http/events/utils.go, bcs-services/bcs-storage/storage/clean/cleaner.go
bcs-k8s-watch:
1. sync once at startup.
2. make eventTime not null.
3. increase http client request retry times.
4. using the correct url to get events.
5. sync get all records using offset.
bcs-storage:
1. clean items that soft deleted in db dynamic.
2. add eventTime index to db event to increase sorting performance.
=> fix: bcs-k8s-watch and bcs-storage bugfix.

bcs-services/bcs-gateway-discovery/app/adapter.go
=> [feature] gateway-discovery 适配webconsole服务发现

bcs-ui/frontend/src/views/app/container.css, bcs-ui/frontend/src/views/app/instance.css, bcs-ui/frontend/src/views/cluster/container.vue, bcs-ui/frontend/src/views/cluster/node-overview.vue, bcs-ui/frontend/src/views/crdcontroller/log_list.vue
=> feat: 日志采集-文件路径tip文案调整

bcs-ui/frontend/src/components/node-selector/index.vue
=> feat: LoadBalancer 获取节点接口调整

bcs-common/go.mod, bcs-common/pkg/bcsapi/storage.go, bcs-common/pkg/bcsapi/storage/object.go, bcs-common/pkg/bcsapi/test/storage_test.go, bcs-common/pkg/esb/client/request.go
修复了一些bcsapi stoarge的请求错误问题，采用limit和offset提升性能和解决数据不全。
=> fix: bcs common bcsapi storage bugfix

bcs-services/bcs-webconsole/app/app.go, bcs-services/bcs-webconsole/app/options/options.go, bcs-services/bcs-webconsole/console/config/config.go, bcs-services/bcs-webconsole/console/config/credential.go, bcs-services/bcs-webconsole/route/middleware.go, bcs-services/bcs-webconsole/route/permissions.go
- 多配置文件watch
- 修复凭证为匹配app_code Bug
- 支持管理员类型凭证
=> Feat: bcs-webconsole 支持管理员凭证

bcs-runtime/bcs-k8s/kubernetes/apis/networkextension/v1/portbinding_types.go
=> fix: 修复 bcs-ingress-controller 端口池释放问题

Makefile
=> fix: fix name.

bcs-runtime/bcs-k8s/bcs-component/bcs-gamedeployment-operator/pkg/update/gamedeployment_update.go, bcs-runtime/bcs-k8s/bcs-component/bcs-gamestatefulset-operator/pkg/controllers/game_stateful_set_control.go
=> fix(gameworkload): fix post hook events

bcs-ui/backend/components/bcs/__init__.py, bcs-ui/backend/settings/base.py, bcs-ui/backend/settings/helm/base.py, bcs-ui/backend/settings/helm/prod.py, bcs-ui/backend/utils/client.py
- 增加 APIGW_URL_TMPL，渲染各网关 url
- 权限中心访问方式修改为通过 APIGW
- BCS_API_HOST 调整为默认从 env 获取
=> minor: use apigw to request iam

docs/features/prometheus/grafana/bcs-gamedeployment-operator-SLA.json
=> fix : 更正GameDeployment dashboard 配置

bcs-services/bcs-webconsole/Dockerfile, bcs-services/bcs-webconsole/Makefile, bcs-services/bcs-webconsole/app/app.go, bcs-services/bcs-webconsole/console/components/bcs/project.go, bcs-services/bcs-webconsole/console/components/iam/iam.go, bcs-services/bcs-webconsole/console/config/auth.go, bcs-services/bcs-webconsole/console/config/base.go, bcs-services/bcs-webconsole/route/middleware.go, bcs-services/bcs-webconsole/route/permissions.go
=> bcs-7.0.2 version

bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/pkg/metrics/prometheus_metrics.go, bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/pkg/scaler/general.go, bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/pkg/scalercore/cron.go, bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/pkg/scalercore/webhook.go
1. 增加指标scalerExecCounts，以结合原有错误统计相关指标计算成功率
2. 增加scalerExecDuration，统计scaler执行时间
3. 增加scaleUpdateDuration，统计更新副本时间
=> feature: 完善原有prom指标以满足GPA SLA需求

docs/features/prometheus/bcs-k8s/bcs-general-pod-autoscaler的SLA监测指标.md, docs/features/prometheus/grafana/bcs-general-pod-autoscaler-SLA.json
=> feature: add grafana dashboard for gpa SLA

bcs-runtime/bcs-k8s/bcs-network/bcs-ingress-controller/portpoolcontroller/portpoolitem.go
=> fix: bcs-ingress-controller 端口池删除会删除lb其他 listener

bcs-services/bcs-data-manager/cmd/options.go, bcs-services/bcs-data-manager/cmd/server.go, bcs-services/bcs-data-manager/image/bcs-data-manager.json.template, bcs-services/bcs-data-manager/pkg/utils/utils.go, bcs-services/bcs-data-manager/pkg/worker/producer.go, install/conf/bcs-services/bcs-data-manager/bcs-data-manager.json.template
=> perf: 新增producer并发配置参数

bcs-common/pkg/bcsapi/storage.go, bcs-common/pkg/bcsapi/storage/object.go, bcs-common/pkg/bcsapi/storage/tkex/generalpodautoscaler/v1alpha1/generalpodautoscaler.go
=> feat: bcs-api bcs-storage add support for hpa and gpa.

bcs-services/bcs-k8s-watch/app/k8s/manager.go, bcs-services/bcs-k8s-watch/app/k8s/resources/default.go, bcs-services/bcs-k8s-watch/go.mod
=> Feat: bcs-k8s-watch add support hpa gpa

bcs-services/bcs-k8s-watch/app/k8s/manager.go, bcs-services/bcs-k8s-watch/app/k8s/watcher.go, bcs-services/bcs-k8s-watch/app/options/options.go, bcs-services/bcs-k8s-watch/app/output/action/alertor.go, bcs-services/bcs-k8s-watch/app/output/action/log.go, bcs-services/bcs-k8s-watch/app/output/http/client.go, bcs-services/bcs-k8s-watch/app/output/writer.go, bcs-services/bcs-k8s-watch/pkg/discovery/bcs/leaderelection.go, bcs-services/bcs-k8s-watch/pkg/discovery/bcs/role.go, bcs-services/bcs-k8s-watch/pkg/discovery/register/node.go, bcs-services/bcs-k8s-watch/pkg/discovery/register/register.go, bcs-services/bcs-k8s-watch/pkg/kubefed/apis/core/v1alpha1/propagatedversion_types.go, bcs-services/bcs-k8s-watch/pkg/kubefed/apis/core/v1beta1/federatedtypeconfig_types.go, bcs-services/bcs-k8s-watch/pkg/kubefed/apis/core/v1beta1/kubefedconfig_types.go, install/conf/bcs-services/bcs-k8s-watch/Dockerfile, install/conf/bcs-services/bcs-k8s-watch/bcs-k8s-watch.json.template
=> feat: bcs k8s watch support label selector

bcs-services/bcs-webconsole/.dockerignore, bcs-services/bcs-webconsole/Dockerfile, bcs-services/bcs-webconsole/console/config/base.go, bcs-services/bcs-webconsole/console/manager/conn.go, bcs-services/bcs-webconsole/console/podmanager/startup.go, bcs-services/bcs-webconsole/go.mod, bcs-services/bcs-webconsole/go.sum, bcs-services/bcs-webconsole/route/middleware.go, bcs-services/bcs-webconsole/route/permissions.go, install/conf/bcs-services/bcs-monitor/Dockerfile, install/conf/bcs-services/bcs-webconsole/Dockerfile
- 修复部分特殊用户名称不能登入Bug
- 使用内置的tzdata数据
=> Fix: bcs-webconsole makeSlugName

bcs-services/bcs-data-manager/pkg/metric/utils.go
问题：query label里有image导致kube_pod_container_resource_requests_cpu_cores查询失败
修改方案：去掉image!=""
=> bugfix: promql查询条件优化

docs/features/prometheus/bcs-services/bcs-storage服务SLA指标.md, docs/features/prometheus/grafana/bcs-storage-sla.json
1.  数据查询
- 数据查询成功率
- 数据查询延迟
2. 数据上报/更新
- 数据更新成功率
- 数据新增延迟<250ms
3. 数据删除
- 数据删除成功率
- 数据删除延迟
=> feature: add grafana dashboard for bcs-storage SLA

bcs-services/bcs-client/go.mod, bcs-services/bcs-user-manager/app/app.go, bcs-services/bcs-user-manager/app/pkg/auth/auth.go, bcs-services/bcs-user-manager/app/pkg/auth/auth_test.go, bcs-services/bcs-user-manager/app/pkg/auth/types.go, bcs-services/bcs-user-manager/app/pkg/cmanager/cmanager.go, bcs-services/bcs-user-manager/app/pkg/passcc/cc.go, bcs-services/bcs-user-manager/app/pkg/passcc/cc_test.go, bcs-services/bcs-user-manager/app/pkg/passcc/types.go, bcs-services/bcs-user-manager/app/pkg/utils/id.go, bcs-services/bcs-user-manager/app/user-manager/user-manager.go, bcs-services/bcs-user-manager/app/user-manager/v1http/permission/permission.go, bcs-services/bcs-user-manager/app/user-manager/v1http/permission/types.go, bcs-services/bcs-user-manager/app/user-manager/v1http/permission/verify.go, bcs-services/bcs-user-manager/config/config.go, bcs-services/bcs-user-manager/go.mod, bcs-services/bcs-user-manager/options/options.go, install/conf/bcs-services/bcs-user-manager/bcs-user-manager.json.template
=> feature: bcs-user-manager support common cluster permission

bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/autoscaling_client.go
=> fix: meet for bcs-k8s-watch client-go version.

bcs-services/bcs-cli/bcs-project-manager/README.md, bcs-services/bcs-cli/bcs-project-manager/cmd/list.go, bcs-services/bcs-cli/bcs-project-manager/cmd/printer/project.go, bcs-services/bcs-cli/bcs-project-manager/cmd/root.go, bcs-services/bcs-cli/bcs-project-manager/cmd/update.go, bcs-services/bcs-cli/bcs-project-manager/go.mod, bcs-services/bcs-cli/bcs-project-manager/pkg/client.go, bcs-services/bcs-cli/bcs-project-manager/pkg/client_test.go
- 项目列表新增分页
- 优化编辑子命令功能
- 代码遵循规范开发
- 相关issue: https://github.com/Tencent/bk-bcs/issues/1911
=> Add: bcs-project-manager client

bcs-services/bcs-cli/bcs-project-manager/cmd/create/create.go, bcs-services/bcs-cli/bcs-project-manager/cmd/create/create_variable.go, bcs-services/bcs-cli/bcs-project-manager/cmd/delete/delete.go, bcs-services/bcs-cli/bcs-project-manager/cmd/delete/delete_variable.go, bcs-services/bcs-cli/bcs-project-manager/cmd/edit/edit.go, bcs-services/bcs-cli/bcs-project-manager/cmd/edit/edit_variable.go, bcs-services/bcs-cli/bcs-project-manager/cmd/get/get_project.go, bcs-services/bcs-cli/bcs-project-manager/cmd/get/get_variable.go, bcs-services/bcs-cli/bcs-project-manager/cmd/render/render.go, bcs-services/bcs-cli/bcs-project-manager/cmd/render/render_variable.go, bcs-services/bcs-cli/bcs-project-manager/cmd/root.go, bcs-services/bcs-cli/bcs-project-manager/pkg/client.go, bcs-services/bcs-cli/bcs-project-manager/pkg/project.go, bcs-services/bcs-cli/bcs-project-manager/pkg/variable.go
- 新增变量管理(variable)操作，包含list, create, delete, update(默认值和备注)
- 新增变量管理渲染(render), 通过 项目code/clusterID/namespace 渲染实际值
- 相关issues: https://github.com/Tencent/bk-bcs/issues/1921
=> Add: bcs-project-manager 新增变量管理相关操作

bcs-services/cluster-resources/pkg/action/resource/resource.go
添加Label:
- webapp.bkbcs.tencent.com/updator： 更新人
- webapp.bkbcs.tencent.com/creator： 创建人
- 相关issue: https://github.com/Tencent/bk-bcs/issues/1933
=> cluster-resources 资源视图新增创建人/更新人字段.

bcs-services/bcs-cli/bcs-project-manager/cmd/create/create.go, bcs-services/bcs-cli/bcs-project-manager/cmd/create/create_clusters_namespace.go, bcs-services/bcs-cli/bcs-project-manager/cmd/delete/delete.go, bcs-services/bcs-cli/bcs-project-manager/cmd/delete/delete_clusters_namespace.go, bcs-services/bcs-cli/bcs-project-manager/cmd/edit/edit.go, bcs-services/bcs-cli/bcs-project-manager/cmd/edit/edit_clusters_namespace.go, bcs-services/bcs-cli/bcs-project-manager/cmd/get/get.go, bcs-services/bcs-cli/bcs-project-manager/cmd/get/get_clusters_namespace.go, bcs-services/bcs-cli/bcs-project-manager/cmd/printer/project.go, bcs-services/bcs-cli/bcs-project-manager/go.mod, bcs-services/bcs-cli/bcs-project-manager/pkg/cluster.go, bcs-services/bcs-cli/bcs-project-manager/pkg/create/yaml_json_param.go, bcs-services/bcs-cli/bcs-project-manager/pkg/namespace.go
- 新增命名空间操作工具
- 编辑命名空间时只能修改Quota相关数据
- 相关issue: https://github.com/Tencent/bk-bcs/issues/1928
=> bcs-project-manager 新增命名空间， Quota管理相关操作

bcs-services/bcs-cli/bcs-user-manager/pkg/token.go, bcs-services/bcs-cli/bcs-user-manager/pkg/user.go
=> 修复 bcs-user-manager cli 代码不规范问题
